services:
  - type: worker
    name: my-worker
    plan: free
    env: docker

    buildCommand: ""        # Dockerfile already handles build
    startCommand: "python3 main.py"

    dockerfilePath: "./Dockerfile"

    autoDeploy: true
    branch: main
